# Generated by Django 5.2.12 on 2026-03-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testimonials", "0003_testimonial_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="content_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="content_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="content_rn",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="content_sw",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
