# Generated by Django 5.0.4 on 2026-03-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0011_remove_sitesettings_about_feature1_title_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="section_featured_accent_rn",
            field=models.CharField(blank=True, default="Amavidewo", max_length=100),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="section_featured_desc_rn",
            field=models.TextField(
                blank=True,
                default="Andura ubutumwa n'inyigisho zacu nshasha kugira uheze ukure buri musi.",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="section_testimonials_accent_rn",
            field=models.CharField(blank=True, default="yacu", max_length=100),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="section_testimonials_desc_rn",
            field=models.TextField(
                blank=True, default="Andura intahe z'abafashijwe n'ijambo ry'Imana."
            ),
        ),
    ]
