# Generated by Django 5.0.4 on 2026-03-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0012_alter_sitesettings_section_featured_accent_rn_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="ticker_enabled",
            field=models.BooleanField(
                default=True, help_text="Activer le bandeau défilant type France 24"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="ticker_refresh_interval",
            field=models.IntegerField(
                default=3600,
                help_text="Fréquence de mise à jour des annonces (secondes, ex: 3600 pour 1h)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="ticker_speed",
            field=models.IntegerField(
                default=30,
                help_text="Vitesse de défilement (secondes pour un cycle complet)",
            ),
        ),
    ]
