# Generated by Django 5.0.4 on 2026-03-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0013_sitesettings_ticker_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="ticker_bg_color",
            field=models.CharField(
                default="#e60000",
                help_text="Couleur de fond du bandeau (hex: #RRGGBB)",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="ticker_opacity",
            field=models.IntegerField(
                default=100, help_text="Opacité du bandeau (0 à 100)"
            ),
        ),
    ]
