# Generated by Django 5.0.4 on 2026-03-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0014_sitesettings_ticker_bg_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="hero_badge_en",
            field=models.CharField(
                blank=True, default="✦ Shalom Ministry", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_badge_fr",
            field=models.CharField(
                blank=True, default="✦ Shalom Ministry", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_badge_rn",
            field=models.CharField(
                blank=True, default="✦ Shalom Ministry", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_badge_sw",
            field=models.CharField(
                blank=True, default="✦ Shalom Ministry", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_description_en",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_description_fr",
            field=models.TextField(
                blank=True,
                default="Une plateforme dédiée à la croissance spirituelle et à l'édification du corps du Christ.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_description_rn",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_description_sw",
            field=models.TextField(blank=True, default=""),
        ),
    ]
