# Generated by Django 5.0.4 on 2026-03-05 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0015_sitesettings_hero_badge_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "role_fr",
                    models.CharField(
                        blank=True, default="Membre de l'équipe", max_length=200
                    ),
                ),
                (
                    "role_rn",
                    models.CharField(
                        blank=True, default="Uwizeye umurwi", max_length=200
                    ),
                ),
                (
                    "role_en",
                    models.CharField(blank=True, default="Team Member", max_length=200),
                ),
                (
                    "role_sw",
                    models.CharField(
                        blank=True, default="Mwanachama wa timu", max_length=200
                    ),
                ),
                ("photo", models.ImageField(blank=True, null=True, upload_to="team/")),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Membre de l'équipe",
                "verbose_name_plural": "Membres de l'équipe",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
