# Generated by Django 5.2.12 on 2026-03-11 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0016_teammember"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="contact_hours_en",
            field=models.CharField(
                blank=True, default="Mon - Fri: 08:00 - 18:00", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="contact_hours_fr",
            field=models.CharField(
                blank=True, default="Lun - Ven : 08:00 - 18:00", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="contact_hours_rn",
            field=models.CharField(
                blank=True,
                default="Ku wa mbere - Ku wa gatanu : 08:00 - 18:00",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="contact_hours_sw",
            field=models.CharField(
                blank=True, default="Jumatatu - Ijumaa: 08:00 - 18:00", max_length=200
            ),
        ),
    ]
