# Generated by Django 5.2.12 on 2026-03-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0017_sitesettings_contact_hours_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="contact_address_en",
            field=models.TextField(blank=True, default="Bujumbura, Burundi"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="contact_address_fr",
            field=models.TextField(blank=True, default="Bujumbura, Burundi"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="contact_address_rn",
            field=models.TextField(blank=True, default="Bujumbura, Burundi"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="contact_address_sw",
            field=models.TextField(blank=True, default="Bujumbura, Burundi"),
        ),
    ]
