# Generated by Django 5.2.12 on 2026-03-12 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0018_sitesettings_contact_address_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="tiktok_url",
            field=models.URLField(blank=True),
        ),
    ]
