# Generated by Django 5.2.12 on 2026-03-12 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediafile",
            name="external_url",
            field=models.URLField(
                blank=True,
                help_text="URL of the external media",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mediafile",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="library/%Y/%m/"),
        ),
    ]
