# Generated by Django 5.0.4 on 2026-03-05 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="content_en",
            field=models.TextField(blank=True, null=True, verbose_name="Contenu (EN)"),
        ),
        migrations.AddField(
            model_name="announcement",
            name="content_fr",
            field=models.TextField(blank=True, null=True, verbose_name="Contenu (FR)"),
        ),
        migrations.AddField(
            model_name="announcement",
            name="content_rn",
            field=models.TextField(blank=True, null=True, verbose_name="Contenu (RN)"),
        ),
        migrations.AddField(
            model_name="announcement",
            name="content_sw",
            field=models.TextField(blank=True, null=True, verbose_name="Contenu (SW)"),
        ),
        migrations.AddField(
            model_name="announcement",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Titre (EN)"
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="title_fr",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Titre (FR)"
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="title_rn",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Titre (RN)"
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="title_sw",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Titre (SW)"
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
