# Generated by Django 5.0.4 on 2026-05-07 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "announcements",
            "0002_announcement_content_en_announcement_content_fr_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyVerse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_fr", models.TextField(verbose_name="Texte (FR)")),
                (
                    "text_en",
                    models.TextField(blank=True, null=True, verbose_name="Texte (EN)"),
                ),
                (
                    "text_rn",
                    models.TextField(blank=True, null=True, verbose_name="Texte (RN)"),
                ),
                (
                    "text_sw",
                    models.TextField(blank=True, null=True, verbose_name="Texte (SW)"),
                ),
                (
                    "reference",
                    models.CharField(help_text="Ex: Romains 15:13", max_length=100),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="daily_verses/"),
                ),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Verset du jour",
                "verbose_name_plural": "Versets du jour",
                "ordering": ["-published_at"],
            },
        ),
    ]
