# Generated by Django 5.2.12 on 2026-03-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0012_publicproduct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="latitude",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="history",
            name="longitude",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="history",
            name="shop_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="history",
            name="shop_owner",
            field=models.CharField(max_length=100),
        ),
    ]
