# Generated by Django 5.0.4 on 2026-04-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_account_photo_alter_account_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "Utilisateur Simple"),
                    ("team", "Équipe"),
                    ("admin", "Administrateur"),
                ],
                default="user",
                max_length=10,
            ),
        ),
    ]
