# Generated by Django 5.0.4 on 2026-04-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_account_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="role",
            field=models.CharField(
                choices=[("team", "Éditeur"), ("admin", "Administrateur")],
                default="team",
                max_length=10,
            ),
        ),
    ]
