# Generated by Django 5.0.4 on 2026-05-07 09:40

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_account_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="users_banners/"),
        ),
        migrations.AddField(
            model_name="account",
            name="deactivated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="is_banned",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="HistoricalAccount",
            fields=[
                ("id", models.BigIntegerField(blank=True, db_index=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("team", "Éditeur"), ("admin", "Administrateur")],
                        default="team",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("photo", models.TextField(blank=True, max_length=100, null=True)),
                ("banner", models.TextField(blank=True, max_length=100, null=True)),
                (
                    "phone_number",
                    models.CharField(db_index=True, max_length=16, null=True),
                ),
                ("otp_code", models.CharField(editable=False, max_length=5, null=True)),
                ("otp_expire_at", models.DateTimeField(blank=True, null=True)),
                ("email_validated", models.BooleanField(default=False)),
                ("is_banned", models.BooleanField(default=False)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical account",
                "verbose_name_plural": "historical accounts",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
