# Generated by Django 5.0.4 on 2026-01-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="Ou télécharger un fichier vidéo",
                null=True,
                upload_to="lessons/videos/",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(blank=True, help_text="URL YouTube ou lien direct"),
        ),
    ]
