# Generated by Django 5.0.4 on 2026-01-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_lesson_video_file_alter_lesson_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="audio_url",
            field=models.URLField(
                blank=True, help_text="Lien vers un fichier audio ou podcast", null=True
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="video_url",
            field=models.URLField(
                blank=True, help_text="Lien YouTube ou vidéo externe", null=True
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="youtube_url",
            field=models.URLField(
                blank=True, help_text="Lien YouTube spécifique (embed)", null=True
            ),
        ),
    ]
