# Generated by Django 5.0.4 on 2026-01-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_course_audio_url_course_video_url_course_youtube_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="audio_file",
            field=models.FileField(
                blank=True,
                help_text="Ou télécharger un fichier audio",
                null=True,
                upload_to="courses/audio/",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="Ou télécharger un fichier vidéo",
                null=True,
                upload_to="courses/videos/",
            ),
        ),
    ]
