# Generated by Django 5.0.4 on 2026-01-13 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_course_audio_file_course_video_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "content_type",
                    models.CharField(
                        choices=[("course", "Émission"), ("sermon", "Prédication")],
                        max_length=10,
                    ),
                ),
                ("content_id", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "content_type", "content_id"],
                        name="courses_fav_user_id_1dbd70_idx",
                    )
                ],
                "unique_together": {("user", "content_type", "content_id")},
            },
        ),
    ]
