# Generated by Django 5.0.4 on 2026-01-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_favorite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="difficulty",
            field=models.CharField(
                blank=True,
                choices=[
                    ("easy", "Débutant"),
                    ("intermediate", "Intermédiaire"),
                    ("advanced", "Avancé"),
                ],
                max_length=12,
                null=True,
            ),
        ),
    ]
