# Generated by Django 5.2.12 on 2026-03-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sermons", "0003_sermon_content_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="sermoncategory",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sermoncategory",
            name="description_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sermoncategory",
            name="description_rn",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sermoncategory",
            name="name_en",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="sermoncategory",
            name="name_fr",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="sermoncategory",
            name="name_rn",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
