# Generated by Django 5.2.12 on 2026-03-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sermons", "0004_sermoncategory_description_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sermoncategory",
            name="description_sw",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sermoncategory",
            name="name_sw",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
