# Generated by Django 5.2.12 on 2026-03-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sermons", "0005_sermoncategory_description_sw_sermoncategory_name_sw"),
    ]

    operations = [
        migrations.AddField(
            model_name="sermon",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sermon",
            name="description_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sermon",
            name="description_rn",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sermon",
            name="description_sw",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sermon",
            name="title_en",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="sermon",
            name="title_fr",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="sermon",
            name="title_rn",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="sermon",
            name="title_sw",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="sermon",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="sermon",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
