# Generated by Django 5.0.4 on 2026-04-17 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sermons", "0006_sermon_description_en_sermon_description_fr_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SermonComment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("author_name", models.CharField(max_length=100)),
                ("author_email", models.EmailField(max_length=254)),
                ("content", models.TextField()),
                ("is_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sermon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="sermons.sermon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commentaire",
                "verbose_name_plural": "Commentaires",
                "ordering": ["-created_at"],
            },
        ),
    ]
