# Generated by Django 5.0.4 on 2026-05-07 09:40

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sermons", "0007_sermoncomment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sermon",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_sermons",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sermon",
            name="responsible_editor",
            field=models.ForeignKey(
                blank=True,
                help_text="Éditeur responsable de cette émission",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responsible_sermons",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sermon",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_sermons",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="HistoricalSermon",
            fields=[
                ("id", models.BigIntegerField(blank=True, db_index=True)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("video", "Vidéo"),
                            ("audio", "Audio"),
                            ("youtube", "YouTube"),
                        ],
                        default="video",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("title_fr", models.CharField(blank=True, max_length=200, null=True)),
                ("title_en", models.CharField(blank=True, max_length=200, null=True)),
                ("title_rn", models.CharField(blank=True, max_length=200, null=True)),
                ("title_sw", models.CharField(blank=True, max_length=200, null=True)),
                ("slug", models.SlugField(blank=True, max_length=220)),
                ("description", models.TextField(blank=True)),
                ("description_fr", models.TextField(blank=True, null=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_rn", models.TextField(blank=True, null=True)),
                ("description_sw", models.TextField(blank=True, null=True)),
                ("preacher_name", models.CharField(max_length=120)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("fr", "Français"),
                            ("rn", "Kirundi"),
                            ("en", "English"),
                            ("sw", "Kiswahili"),
                        ],
                        default="fr",
                        max_length=2,
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "video_url",
                    models.URLField(blank=True, help_text="URL YouTube ou lien direct"),
                ),
                (
                    "video_file",
                    models.TextField(
                        blank=True,
                        help_text="Ou télécharger un fichier vidéo",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("audio_url", models.URLField(blank=True, help_text="URL audio")),
                (
                    "audio_file",
                    models.TextField(
                        blank=True,
                        help_text="Ou télécharger un fichier audio",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("image", models.TextField(blank=True, max_length=100, null=True)),
                ("featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("sermon_date", models.DateField(blank=True, null=True)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="sermons.sermoncategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsible_editor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Éditeur responsable de cette émission",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical sermon",
                "verbose_name_plural": "historical sermons",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
